# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplan',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='start_date',
            field=models.DateField(),
        ),
    ]
